apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
spec:
  owner: group:default/guests
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
     backstage.io/techdocs-ref: dir:./docs
     github.com/project-slug: ${{ values.repo_owner }}/${{ values.repo_name }}/actions    
spec:
  type: service
  owner: group:default/guests
  lifecycle: experimental
  system: ${{ values.name }}
  providesApis:
    - ${{ values.name }}
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
spec:
  type: internal
  lifecycle: experimental
  owner: group:default/guests
  system: ${{ values.name }}
  definition: "${{ values.description }}"
